server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users
          uri: lb://PHOTOAPPAPI-USERS/users
          predicates:
          - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}


