server:
  port: 8761
eureka:
  instance:
    hostname: http://localhost
    statusPageUrl: http://${eureka.hostname}/info
    healthCheckUrl: http://${eureka.hostname}/health
    homePageUrl: http://${eureka.hostname}/
    lease-renewal-interval-in-seconds: 5
  server:
    a-s-g-update-interval-ms: 5
    peer-eureka-nodes-update-interval-ms: 5
spring:
  application:
    name: PhotoAppApi-eureka-server
  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
ping